[2022-11-24 06:58:21,825] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestationDag.wget scheduled__2022-09-02T06:00:00+00:00 [queued]>
[2022-11-24 06:58:21,862] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestationDag.wget scheduled__2022-09-02T06:00:00+00:00 [queued]>
[2022-11-24 06:58:21,863] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-24 06:58:21,864] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-11-24 06:58:21,865] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-24 06:58:21,900] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-09-02 06:00:00+00:00
[2022-11-24 06:58:21,909] {standard_task_runner.py:52} INFO - Started process 2477 to run task
[2022-11-24 06:58:21,924] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestationDag', 'wget', 'scheduled__2022-09-02T06:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestation.py', '--cfg-path', '/tmp/tmplcuicb4o', '--error-file', '/tmp/tmpv6po577k']
[2022-11-24 06:58:21,928] {standard_task_runner.py:77} INFO - Job 37: Subtask wget
[2022-11-24 06:58:22,099] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestationDag.wget scheduled__2022-09-02T06:00:00+00:00 [running]> on host d01293c252ef
[2022-11-24 06:58:22,269] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestationDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-02T06:00:00+00:00
[2022-11-24 06:58:22,273] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-24 06:58:22,274] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet -O /opt/***/output.csv']
[2022-11-24 06:58:22,294] {subprocess.py:85} INFO - Output:
[2022-11-24 06:58:22,371] {subprocess.py:89} INFO - bash: wget: command not found
[2022-11-24 06:58:22,386] {subprocess.py:93} INFO - Command exited with return code 127
[2022-11-24 06:58:22,479] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-24 06:58:22,524] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestationDag, task_id=wget, execution_date=20220902T060000, start_date=20221124T065821, end_date=20221124T065822
[2022-11-24 06:58:22,567] {standard_task_runner.py:92} ERROR - Failed to execute job 37 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-24 06:58:22,615] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-24 06:58:22,756] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-24 06:58:22,802] {dagrun.py:530} ERROR - Marking run <DagRun LocalIngestationDag @ 2022-09-02 06:00:00+00:00: scheduled__2022-09-02T06:00:00+00:00, externally triggered: False> failed
[2022-11-24 06:58:22,806] {dagrun.py:605} INFO - DagRun Finished: dag_id=LocalIngestationDag, execution_date=2022-09-02 06:00:00+00:00, run_id=scheduled__2022-09-02T06:00:00+00:00, run_start_date=2022-11-24 06:58:14.580358+00:00, run_end_date=2022-11-24 06:58:22.805318+00:00, run_duration=8.22496, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2022-09-02 06:00:00+00:00, data_interval_end=2022-10-02 06:00:00+00:00, dag_hash=86fda678b6f76c6b2db5748c8ad4962c
