[2022-12-02 05:58:33,879] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_upload_dag.remodel_data_type_task scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-12-02 05:58:33,923] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: FHV_data_upload_dag.remodel_data_type_task scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2022-12-02 05:58:33,924] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-02 05:58:33,925] {taskinstance.py:1239} INFO - Starting attempt 14 of 14
[2022-12-02 05:58:33,926] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-02 05:58:33,970] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): remodel_data_type_task> on 2019-02-02 06:00:00+00:00
[2022-12-02 05:58:33,981] {standard_task_runner.py:52} INFO - Started process 7879 to run task
[2022-12-02 05:58:33,990] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'FHV_data_upload_dag', 'remodel_data_type_task', 'scheduled__2019-02-02T06:00:00+00:00', '--job-id', '331', '--raw', '--subdir', 'DAGS_FOLDER/FHV_data_upload_dag.py', '--cfg-path', '/tmp/tmp4ghow2rt', '--error-file', '/tmp/tmp5r_ybdf4']
[2022-12-02 05:58:33,993] {standard_task_runner.py:77} INFO - Job 331: Subtask remodel_data_type_task
[2022-12-02 05:58:34,162] {logging_mixin.py:109} INFO - Running <TaskInstance: FHV_data_upload_dag.remodel_data_type_task scheduled__2019-02-02T06:00:00+00:00 [running]> on host abdcba3d233e
[2022-12-02 05:58:34,347] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-12-02 05:58:34,395] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=FHV_data_upload_dag
AIRFLOW_CTX_TASK_ID=remodel_data_type_task
AIRFLOW_CTX_EXECUTION_DATE=2019-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-02-02T06:00:00+00:00
[2022-12-02 05:58:38,773] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/FHV_data_upload_dag.py", line 68, in remodel_parquet_data_type
    df.to_parquet(dest_file, allow_truncated_timestamps=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 2685, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 423, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 195, in write
    table, path_or_handle, compression=compression, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1987, in write_table
    writer.write_table(table, row_group_size=row_group_size)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 693, in write_table
    self.writer.write_table(table, row_group_size=row_group_size)
  File "pyarrow/_parquet.pyx", line 1439, in pyarrow._parquet.ParquetWriter.write_table
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Casting from timestamp[ns] to timestamp[us] would lose data: -3787364347419103232
[2022-12-02 05:58:38,845] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=FHV_data_upload_dag, task_id=remodel_data_type_task, execution_date=20190202T060000, start_date=20221202T055833, end_date=20221202T055838
[2022-12-02 05:58:38,899] {standard_task_runner.py:92} ERROR - Failed to execute job 331 for task remodel_data_type_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/FHV_data_upload_dag.py", line 68, in remodel_parquet_data_type
    df.to_parquet(dest_file, allow_truncated_timestamps=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 2685, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 423, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 195, in write
    table, path_or_handle, compression=compression, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1987, in write_table
    writer.write_table(table, row_group_size=row_group_size)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 693, in write_table
    self.writer.write_table(table, row_group_size=row_group_size)
  File "pyarrow/_parquet.pyx", line 1439, in pyarrow._parquet.ParquetWriter.write_table
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Casting from timestamp[ns] to timestamp[us] would lose data: -3787364347419103232
[2022-12-02 05:58:39,103] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-02 05:58:39,225] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
