[2022-12-05 04:00:08,890] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_2_bq_dag.bq_ext_2_part_task scheduled__2019-11-02T06:00:00+00:00 [queued]>
[2022-12-05 04:00:08,932] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_2_bq_dag.bq_ext_2_part_task scheduled__2019-11-02T06:00:00+00:00 [queued]>
[2022-12-05 04:00:08,934] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-05 04:00:08,935] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-12-05 04:00:08,936] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-05 04:00:08,982] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2019-11-02 06:00:00+00:00
[2022-12-05 04:00:08,993] {standard_task_runner.py:52} INFO - Started process 11056 to run task
[2022-12-05 04:00:09,011] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_2_bq_dag', 'bq_ext_2_part_task', 'scheduled__2019-11-02T06:00:00+00:00', '--job-id', '465', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestation_gcp.py', '--cfg-path', '/tmp/tmpue4ni5tg', '--error-file', '/tmp/tmp_vuce9ld']
[2022-12-05 04:00:09,013] {standard_task_runner.py:77} INFO - Job 465: Subtask bq_ext_2_part_task
[2022-12-05 04:00:09,171] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_2_bq_dag.bq_ext_2_part_task scheduled__2019-11-02T06:00:00+00:00 [running]> on host 9b5bfd347476
[2022-12-05 04:00:09,428] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2019-11-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-11-02T06:00:00+00:00
[2022-12-05 04:00:09,443] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-12-05 04:00:09,541] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-12-05 04:00:09,649] {bigquery.py:1637} INFO - Inserting job ***_yellow_taxi_2_bq_dag_bq_ext_2_part_task_2019_11_02T06_00_00_00_00_a1c5cbe6fd4838dfcd9a0748bad127cd
[2022-12-05 04:00:11,048] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: trips_data_all.external_yellow_tripdata, error message: Parquet column 'DOLocationID' has type DOUBLE which does not match the target cpp_type INT64. File: gs://my_nyc_tlc/yellow/2019-09.parquet

(job ID: airflow_yellow_taxi_2_bq_dag_bq_ext_2_part_task_2019_11_02T06_00_00_00_00_a1c5cbe6fd4838dfcd9a0748bad127cd)

                       -----Query Job SQL Follows-----                        

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:        CREATE OR REPLACE TABLE trips_data_all.yellow_tripdata_partitoned
   3:        PARTITION BY DATE(tpep_pickup_datetime) AS
   4:        SELECT * FROM trips_data_all.external_yellow_tripdata;
   5:        
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-12-05 04:00:11,089] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=yellow_taxi_2_bq_dag, task_id=bq_ext_2_part_task, execution_date=20191102T060000, start_date=20221205T040008, end_date=20221205T040011
[2022-12-05 04:00:11,130] {standard_task_runner.py:92} ERROR - Failed to execute job 465 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: trips_data_all.external_yellow_tripdata, error message: Parquet column 'DOLocationID' has type DOUBLE which does not match the target cpp_type INT64. File: gs://my_nyc_tlc/yellow/2019-09.parquet

(job ID: airflow_yellow_taxi_2_bq_dag_bq_ext_2_part_task_2019_11_02T06_00_00_00_00_a1c5cbe6fd4838dfcd9a0748bad127cd)

                       -----Query Job SQL Follows-----                        

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:        CREATE OR REPLACE TABLE trips_data_all.yellow_tripdata_partitoned
   3:        PARTITION BY DATE(tpep_pickup_datetime) AS
   4:        SELECT * FROM trips_data_all.external_yellow_tripdata;
   5:        
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-12-05 04:00:11,155] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-05 04:00:11,218] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
